language: objective-c

matrix:
  fast_finish: true
  
before_install:
 - brew install ant
 - wget -O /usr/local/android-sdk_r23.0.2-macosx.zip https://dl.google.com/android/android-sdk_r23.0.2-macosx.zip
 - unzip -d /usr/local /usr/local/android-sdk_r23.0.2-macosx.zip
 - export ANDROID_HOME=/usr/local/android-sdk-macosx
 - export PATH=$PATH:$ANDROID_HOME/tools
 - ( sleep 1 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --all --no-ui --filter platform-tool,android-19,sysimg-19,build-tools-19.1.0,extra-android-support,sys-img-armeabi-v7a-android-19
 
before_script:
 - android update project -t android-19 -p android/.

script:
 - make
 
